export  enum adminRoute {
    RT_CATEGORY = "category",
    MT_CATEGORY= "category",
    RT_PRODUCTS = "products",
    MT_PRODUCTS = "products",
    RT_ORDER = "order",
    MT_ORDER = "orders",
    RT_DASHBOARD = "dashboard",
    MT_DAHBOARD = "dashboard",
    RT_ADMINS = "admin",
    MT_ADMINS = "Admins",
    MT_SINGLE_PRODUCT = "single product",
    RT_SINGLE_PRODUCT = "single product",
    RT_SINGLE_CATEGORY = "single category",
    MT_SINGLE_CATEGORY = "single category",
    RT_SINGLE_ADMIN = "single admin",
    MT_SINGLE_ADMIN = "single admin",
    RT_ADD_PRODUCT = "add product",
    MT_ADD_PRODUCT = "add product",
    RT_ADD_CATEGORY = "add category",
    MT_ADD_CATEGORY = "add category",
    RT_ADD_MEDIA = "add media",
    MT_ADD_MEDIA = "add media",
};
